### ISSUE TITLE
Iron absorption for babies

### ISSUE THREAD

**Issue by iteles** [iteles/blw-baby#2]
From 6 months onwards, babies' iron levels start to deplete, so particular care has to be taken with nutrition in order to make up for this.

## Tasks
+ [ ] Find & document scientific evidence of this
+ [ ] Research best sources of iron (vegetarian and not, but with a focus on vegetarian)
+ [ ] Research and document info on iron absorption and how to improve this (e.g. is it more bio-available in some foods? Non-animal iron sources require vitamin C to be well absorbed, what inhibits iron absorption and any more relevant info)

**Comment by Stephanymtr** [comment]
I have started a basic research on this topic, and I have found quite a few scientific articles. Interestingly, I used to have access to all of them as an uni student, but now I have to create a profile/pay to have access/read... some of them though, not all. Anyways, regarding your first task: by "Find & document", do you mean you would you like me to post here the links to these scientific articles ? 🤔

**Comment by iteles** [comment]
@Stephanymtr Yes please and also summarize what is in each one. 

Ultimately what I would like to have from this issue is a full blog post on iron absorption for babies, with scientific evidence and a simple ' what to do' guide. 

I would also look for existing posts as a reference on the two main sites I keep coming back to: 

https://comidadebebe.pt/?s=Ferro

And solidstarts.com

**Comment by Stephanymtr** [comment]
1 - **[Iron Deficiency Anemia in Predominantly Breastfed Young Children](https://reader.elsevier.com/reader/sd/pii/S1875957214000710?token=BC001652C817CCBB5BE977EB50E622B8AB0947E83863444BC7EE061F49DEE7447CF28DA78D714B8BD58066CACA36BDB6&originRegion=eu-west-1&originCreation=20211228100618)**

https://reader.elsevier.com/reader/sd/pii/S1875957214000710?token=BC001652C817CCBB5BE977EB50E622B8AB0947E83863444BC7EE061F49DEE7447CF28DA78D714B8BD58066CACA36BDB6&originRegion=eu-west-1&originCreation=20211228100618

This study goes over the subtle problem of predominantly breastfed babies developing iron deficiency anemia. Apart from this deficiency’s presentation being elusive, it’s caused due to the lack of knowledge in implementing complimentary food to a breastfed diet. On this study, none of the 15 subjects (breastfed babies) was suspected to have anemia by their caregivers, and detection relied mainly on alert medical personnel.

**Comment by Stephanymtr** [comment]
2 - **[A Substantial Proportion of 6- to 12-Month-Old Infants Have Calculated Daily Absorbed Iron below Recommendations, Especially Those Who Are Breastfed](https://reader.elsevier.com/reader/sd/pii/S0022347620313706?token=7C11E04B40BC84EDAC33B1F5B9F616EC48298A20A77703935B563580A6613DE0E7B67E0E32AA02BB828F6B086118C882&originRegion=eu-west-1&originCreation=20211228124540 )**

https://reader.elsevier.com/reader/sd/pii/S0022347620313706?token=7C11E04B40BC84EDAC33B1F5B9F616EC48298A20A77703935B563580A6613DE0E7B67E0E32AA02BB828F6B086118C882&originRegion=eu-west-1&originCreation=20211228124540 

This study is very interesting as it touches up on your 3rd task. They focused on calculating the amount of bioavailability iron consumed among infants. Based on this article, the 6- to 12- month-old group of subjects included infants who were on a full or partial breastfeeding diet, as well as some infants who weren’t breastfeeding. The calculated absorbed iron based on current feeding patterns were BELOW that needed to meet requirements for growth and red blood cells production. The study also demonstrated that there is minimal iron intake in ALL groups from highly bioavailable heme iron sources. Interestingly, low iron intakes were very similar both in 6- to 9-month-old and 9- to 12-month-old infants, demonstrating no tendency toward increased heme iron intake after solid food consumption was well-established. The study believes that all children should be monitored for clinical check up of low iron status; and that although formula-fed infants are at lower risk, they encourage increasing the proportion of heme iron obtained from animal products in their diet where feasible.

**Comment by Stephanymtr** [comment]
SIDE NOTE: During my research, I keep bumping into some interesting, but costly articles. So, after some googling, I bumped into this [website](https://sci-hub.se/) that provides access to academic papers and articles using educational institution access, and its own cache of downloaded papers and articles. I know this is cheating! #Guilty, but worth it??  For instance, I found this study “[Are Breastfed Infants Iron Deficient? The Question That Won't Go Away](https://www.sciencedirect.com/science/article/abs/pii/S0022347620314931)” for $35.95 Once I pasted it on there, I gained immediate access to it. I know this is a big potential copyright infringement, but still wanted to share it here as this is mind-blowing. I will continue looking for just as good and free studies though! 🧑‍🎓

**Comment by Stephanymtr** [comment]
3 – **[THE OPTIMAL DURATION OF EXCLUSIVE BREASTFEEDING](https://www.who.int/nutrition/publications/optimal_duration_of_exc_bfeeding_report_eng.pdf)**

 https://www.who.int/nutrition/publications/optimal_duration_of_exc_bfeeding_report_eng.pdf

The goal of this article from the World Health Organization was to assess the scientific evidence and create recommendations on the ideal duration of exclusive breastfeeding; This article reviews multiple other studies as well comparing exclusive breastfeeding for 4 to 6 months, versus 6 months, in terms of growth, infant iron status, motor development, and others. Given our focus on the iron topic, the study showed inferior iron status in infants exclusively breastfed for 6 months, versus 4 months followed by partial breastfeeding to 6 months. Although they believe exclusive breastfeeding to 6 months can lead to iron deficiency in vulnerable infants, the risks must be evaluated against the benefits provided by exclusive breastfeeding, especially the potential reduction in morbidity and mortality.

**Comment by nelsonic** [comment]
Yeah, Sci-Hub is a good source for the absurdly over-priced articles. It’s not legal though … https://en.m.wikipedia.org/wiki/Sci-Hub 
So while we can use it in the short-term for doing research, longer term we should favour open access articles e.g PubMed: https://pubmed.ncbi.nlm.nih.gov/ 👍🏻

**Comment by Stephanymtr** [comment]
4- **[Diagnosis and prevention of iron deficiency and iron-deficiency anemia in infants and young children (0–3 years of age)](https://watermark.silverchair.com/zpe01110001040.pdf?token=AQECAHi208BE49Ooan9kkhW_Ercy7Dm3ZL_9Cf3qfKAc485ysgAAAt0wggLZBgkqhkiG9w0BBwagggLKMIICxgIBADCCAr8GCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMaUpSEu_Syc59h4CRAgEQgIICkEjKua1ydCq9Yz9mVUcw3tm1S_DdYD8mUTHEHhGpwG2X-8FY_KbTyddu3i5qz7TZJ99gvcuYzTlX2ZyYdWs_PCCKMafbwyL0fTMUu0i48iFvPTQn6SrOz5hwpUZeT3jpyVVwNQ-L09B-SPseZZ1uVyJSfEj9PbCuJjdTGZbWWd46OqJ0HsIql5B5xsT-8BU4ts5ej8q_CMXFSo8FdxT6inPD26M3HtTFy1zXtJLcA6JIZj_5GA91hxDcSdVyU_IQt8hgAs_sY1I7VAZGNXkhNrLXr8IvbpXr-lOMmttaTsCBbqJtMrKjBs4iESMaA8MuwciCtGaOX-DXFSafqN53R2tk1CQaB5AUyUtb3OI04HQt4Q1fp0VsSfpQJpIq1Z16vbfUOySXDb6QOTzrqjwLRl6D_XlC0PcV8Y-wFGCkNERDw_oP00bHccB6yZB5_XPrHojV9V2kUIiL6EDGcWA1vVrO0gtgtbfFO69MtujrpKr1wivSPxvbzvvtXmbiZrDopV_nUzGLC48pfldGuh1E0f2QFxV2AI6sWQyRbB3p9BsqVl965unNDP8A9qa640giDc5Xc0LRjeDkDT3k83e03gcxPnWE1Og5CeeHG_Z6sGmAeCdxrlxe10y0DL1Ex_P9KaDs4hsjwQi_DgOrS2CdKkN7KvxeWQ-1b9KBrc_JWzxQbxP083B7LOgiYlsUG5UuUpu5oTDeShRO08QY8y5M-54jce1xXqYOpLN5EHxIZe9LKhYMZir0Ob3CYKHqBJ0cgNVKy4swKzAXGmrflAxrymSLIRPJsg6QEKBighejfZh7CmAGoYU9jXO7olHQ0bl1kn2PRGq2pxE9b3eSfeBtla3d1MZRqts0ct2Nfq6Zt59D)**

https://watermark.silverchair.com/zpe01110001040.pdf?token=AQECAHi208BE49Ooan9kkhW_Ercy7Dm3ZL_9Cf3qfKAc485ysgAAAt0wggLZBgkqhkiG9w0BBwagggLKMIICxgIBADCCAr8GCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMaUpSEu_Syc59h4CRAgEQgIICkEjKua1ydCq9Yz9mVUcw3tm1S_DdYD8mUTHEHhGpwG2X-8FY_KbTyddu3i5qz7TZJ99gvcuYzTlX2ZyYdWs_PCCKMafbwyL0fTMUu0i48iFvPTQn6SrOz5hwpUZeT3jpyVVwNQ-L09B-SPseZZ1uVyJSfEj9PbCuJjdTGZbWWd46OqJ0HsIql5B5xsT-8BU4ts5ej8q_CMXFSo8FdxT6inPD26M3HtTFy1zXtJLcA6JIZj_5GA91hxDcSdVyU_IQt8hgAs_sY1I7VAZGNXkhNrLXr8IvbpXr-lOMmttaTsCBbqJtMrKjBs4iESMaA8MuwciCtGaOX-DXFSafqN53R2tk1CQaB5AUyUtb3OI04HQt4Q1fp0VsSfpQJpIq1Z16vbfUOySXDb6QOTzrqjwLRl6D_XlC0PcV8Y-wFGCkNERDw_oP00bHccB6yZB5_XPrHojV9V2kUIiL6EDGcWA1vVrO0gtgtbfFO69MtujrpKr1wivSPxvbzvvtXmbiZrDopV_nUzGLC48pfldGuh1E0f2QFxV2AI6sWQyRbB3p9BsqVl965unNDP8A9qa640giDc5Xc0LRjeDkDT3k83e03gcxPnWE1Og5CeeHG_Z6sGmAeCdxrlxe10y0DL1Ex_P9KaDs4hsjwQi_DgOrS2CdKkN7KvxeWQ-1b9KBrc_JWzxQbxP083B7LOgiYlsUG5UuUpu5oTDeShRO08QY8y5M-54jce1xXqYOpLN5EHxIZe9LKhYMZir0Ob3CYKHqBJ0cgNVKy4swKzAXGmrflAxrymSLIRPJsg6QEKBighejfZh7CmAGoYU9jXO7olHQ0bl1kn2PRGq2pxE9b3eSfeBtla3d1MZRqts0ct2Nfq6Zt59D

This clinical study offers diagnosis and prevention of iron deficiency and iron-deficiency anemia in infants (both breastfed and formula fed) and toddlers from birth through 3 years of age. They believe health care providers should be working to end iron deficiency by creating better methods used for screening. Although this article establishes that there needs to have higher levels of evidence to settle controversies regarding the timing and methods used for screening for iron deficiency and iron-deficiency anemia, they offered a long list of multiple evidence-based recommendations for the issue. For example, their very first recommendation is that “at 4 months of age, breastfed infants should be supplemented with 1 mg/kg per day of oral iron beginning at 4 months of age until appropriate iron-containing complementary foods are introduced in the diet”

**Comment by Stephanymtr** [comment]
Future reminder: the recommendations from the previous article/study I posted above are pretty awesome! It would be great to add them to our blog post**

**Comment by Stephanymtr** [comment]
**Research best sources of iron (vegetarian and not, but with a focus on vegetarian)**

The study I posted above has a table of foods naturally rich in iron: Table 3. You can find it on page 7 and 8 of the study. I will also post it here a screenshot of it as well. According to the study, 7mg/day is the ideal amount of iron for children of 1-3 years of age. They believe that once the iron requirements of toddlers are met, their iron deficiency and iron-deficiency anemia could be prevented with food naturally rich in iron. They included heme sources of iron (ie, red meat) and nonheme sources of iron (ie, legumes, iron-fortified cereals).

![image](https://user-images.githubusercontent.com/91985721/147590232-a99f6f0a-ee8c-491b-94ec-00a41fba7edb.png)

**Comment by Stephanymtr** [comment]
**Research best sources of iron (vegetarian and not, but with a focus on vegetarian)**

5 - [**Article: Meeting the nutrient reference values on a vegetarian diet**](https://www.mja.com.au/system/files/issues/196_10_040612_supplement/rei11510_fm.pdf)

https://www.mja.com.au/system/files/issues/196_10_040612_supplement/rei11510_fm.pdf

This study confirms that a well-organized vegetarian diet can meet almost all the nutritional needs of children and adults of all ages. The study offers sample meal plans available online, so I’m attaching the pdf link below. Since the increased iron requirement for vegetarians was successfully achieved for most of their meal plans (with the exception of pregnant females), I think it’s worth checking these meal plans out.

http://www.sanitarium.com.au/getmedia/bc7fcfd3-b81c-4102-bdf8-9ba7e689c8ba/Sanitarium-Sample-Meal-Plans-and-Analyses.pdf

Some of these meal plans contain eggs, but not all of them 😃 
_page 3 – 1 year old / page 4 – 2 years old / page 5 – 3 years old_

According to this article, the best vegetarian sources of iron in their meal plans were firm **tofu, iron-fortified breads and breakfast cereals, cashews, chickpeas, pumpkin seeds, sesame seeds, brown rice, fortified malted chocolate powder and tabouli.**

**Comment by Stephanymtr** [comment]
Quick update: After reading all day, I was able to gather & document scientific evidence on iron deficiency. I'm sure we can never have too many studies on this topic, but it also didn't feel right spending all day on one task. Therefore, I posted here a couple of the good ones I found during my research along with a short summary. I then moved on to my next task and started researching the best sources of iron. I can always go back to these tasks if we think we need more evidence/content as well. I ran out of time, but tomorrow I'm planning to look for one, maybe two more articles on the the second task, and then move on to my third and final task:  :) Let me know if you guys have questions or suggestion. Thank you!

**Comment by Stephanymtr** [comment]
Research best sources of iron (vegetarian and not, but with a focus on vegetarian)

6- **[Vegetarian diet: How to get the best nutrition](https://www.mayoclinic.org/healthy-lifestyle/nutrition-and-healthy-eating/in-depth/vegetarian-diet/art-20046446)**

https://www.mayoclinic.org/healthy-lifestyle/nutrition-and-healthy-eating/in-depth/vegetarian-diet/art-20046446

According to the article above, good sources of iron are dried beans, **peas, lentils, enriched cereals, whole-grain products, dark leafy green vegetables, and dried fruit.**

**Comment by Stephanymtr** [comment]
### Enhancing iron absorption
 **Research and document info on iron absorption and how to improve this (e.g. is it more bio-available in some foods? Non-animal iron sources require vitamin C to be well absorbed, what inhibits iron absorption and any more relevant info)**
7 - [Vegetarian diet: How to get the best nutrition](https://www.mayoclinic.org/healthy-lifestyle/nutrition-and-healthy-eating/in-depth/vegetarian-diet/art-20046446)
8 - [Iron intake for vegetarians](https://www.mydr.com.au/iron-intake-for-vegetarians/)
 Because we are focusing on a vegetarian diet, we should be aware that iron isn't as easily absorbed from plant sources. **HOWEVER**, if paired with eating foods rich in vitamin C, it will make iron containing foods more easily absorbed by your body. According to the articles above, foods with **vitamin C are: strawberries, citrus fruits, tomatoes, cabbage and broccoli.**

**Comment by Stephanymtr** [comment]
### Enhancing iron absorption

**Research and document info on iron absorption and how to improve this (e.g. is it more bio-available in some foods? Non-animal iron sources require vitamin C to be well absorbed, what inhibits iron absorption and any more relevant info)**

9 - Iron bioavailability and dietary reference values
https://academic.oup.com/ajcn/article/91/5/1461S/4597424

According to the study above bioavailability is defined as the extent to which iron is absorbed from the diet and used for normal body functions.

10 - [Iron Absorption](https://sci-hub.se/https://www.annualreviews.org/doi/pdf/10.1146/annurev.me.34.020183.000415)
https://sci-hub.se/https://www.annualreviews.org/doi/pdf/10.1146/annurev.me.34.020183.000415

Based on the study above, the lack of heme (comes from animals) and bioavailability of the nonheme (comes from plants) iron in the diets of many individuals leads to a low amount of iron absorption.  Children, teenagers, women and pregnant women require a more well-planned iron intake in their diets as they tend to be the ones who cannot absorb enough. 

The study also says, “the influence of the ligands present in a particular foodstuff is not limited to the iron in that food. but extends to all the nonheme iron that happens to be present at the same time within the lumen of the gastrointestinal tract, whatever its origin”. This means what will really determine how much iron can be absorbed is the structure of each dish. The example shared in the study was of a person eating rice and drinking orange juice. They will absorb a much higher proportion of the rice iron, instead of someone eating rice and drinking tea as the iron amount absorbed will be much lower.

**Comment by Stephanymtr** [comment]
[11 - **Iron bioavailability and dietary reference values**](https://watermark.silverchair.com/1461s.pdf?token=AQECAHi208BE49Ooan9kkhW_Ercy7Dm3ZL_9Cf3qfKAc485ysgAAAsgwggLEBgkqhkiG9w0BBwagggK1MIICsQIBADCCAqoGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMkHggu9yZnVh76qv1AgEQgIICe8sfrHNwVmAYs2WHEvQAvh_HYC_gIIywnPBrWxU7mQ3htoOm_uo2ocCAubQjPI7i0Wfjq1ov8zsbuvWg9aQmntXqlLdJng106XLf_TtlckVoCEMsb40v4UyQdY8YpkiV9wf33LWkES9Qjk3HEyBZiWNGZWwqCBEQ4yZzOSJFD-dZ5eKKW1P-xAfHyRSo6hmsBh1EKmAB9Pv3pE95osIVNtUOCyMR6HWExsJOqgmMK4uUoPBYigWSTvG-8P99LuwxzTy7cGA-ta2FM_2MAOOvH539-IUQTVHDYVdOl3RRfx7Gx9z4umHPDOsKTZf3N5a3BQde0crKNpBMoupKxZ3AxtUb5H0QLs3Pz7eZWkuFTsOETr_adjFVwhQzNS-f-EVg89HXuPHuE1-YS96pPI0FGEiE5GzvukD4DeKwX51XI81glbjtoZB6zZHH8D_CfgUw9i62Qv8S3QrQXjM8y7aKMtVd2JRC1LK91JG-aExjKjB9sgJaTmRJqam-4BrjZbLytt2xns_xK1URCUgfmn2Iws5fda-u42fQfuKeTbEWlxll0s5WvhhFBaOdm8JGEot62k4wRDNiwYwfwkdnIS_YQfQLsJ530lxRqbGIJK4PnLPchM4JN0cIyvn-WERGqoUkayqjUjh5tnYJMZe4twpp0vZGK1BeUtaeq8I1jJa952FPWIe_pbmnGlM_THj_I-hOCtiZjK9mq2XzPnfJI3YXxkV97fepgXRA_pwGZk_K4Uo4HOAfKs7vrNZWkyT0Zjrw-Vqq6us84gIolkPFyVbccs1hrG6puUv0bb2WuTTv-XF-Oz6VER0hwjhI298G1bNzQ0mBGwRUsBJ5Fl7h
)

According to this article, cereal foods are normally fortified with low-bioavailability elemental iron powders, so a high intake of fortification iron would be expected to lower dietary bioavailability. Unfortunately, it is difficult to estimate the contribution of fortification iron to the bioavailability factors as the consumption of these compounds can differ widely.

12- [**Interaction of vitamin C and iron**](https://www.clinicaltrials.gov/ct2/show/NCT00570895)

I found this interesting clinical study that measured the iron absorption in children from meals containing ferrous fumarate (iron) with and without vitamin C and their final data demonstrated an overall benefit to iron absorption from ferrous fumarate from meals with vitamin C

13- **[Vitamin C](https://ods.od.nih.gov/factsheets/VitaminC-HealthProfessional/)**
https://ods.od.nih.gov/factsheets/VitaminC-HealthProfessional/

The National Institute of Health created a Recommended Dietary Allowances list for vitamin C:

![image](https://user-images.githubusercontent.com/91985721/147671161-10bba7c7-e988-4a4f-b27b-2b7a9c607121.png)


Fruits and vegetables are the best sources of vitamin C, so below are some of the NIH's Vitamin C Content of Selected Foods: 

 
![image](https://user-images.githubusercontent.com/91985721/147671207-b0ca4e1d-bb25-4bc6-98cf-d8180ab88bee.png)

**Comment by Stephanymtr** [comment]
@iteles Like I mentioned above, I'm sure we can never have too many studies on this topic, but I think I have gathered good content here. Let me know what you think whenever you look at my comments. I'm happy to come back later if you think we need more evidence/content as well. Meanwhile, I'll go ahead and move on to recipes issues.
