### ISSUE TITLE
Chia Eggs: How to Replace Poultry Eggs with a Plant-based Alternative

### ISSUE THREAD

**Issue by nelsonic** [iteles/blw-baby#25]
This is a _micro_ piece of content that we can create in around **`T1h`**.

# Todo

## Research

+ [ ] Take a look at the existing web pages/sites listed on the first page of Google results (max 8)
  + [ ] Use an incognito Chrome (or Brave) window to avoid any cookies/trackers
  + [ ] Screenshot the _first_ thing you see when you open the page e.g. the annoying cookie modal/prompt below.
    > See: https://www.take-a-screenshot.org/mac.html
  + [ ] Once you've dismissed the cookie noise, take _another_ screenshot of actual content to show the layout, any Ads, and show how much cruft there is on the page. i.e. do they get straight to the point or is there a lot of noise?

## Create!

Once you have looked at the available top recipes for a Chia Egg and uploaded all the screenshots for the research.

+ [ ] Plan the photograph we are going to take for our recipe:
  + [ ] What background do you want to use, do you want anything else in the frame?
+ [ ] Take the photos of raw ingredients, process and final result
+ [ ] Do any necessary post-processing of images e.g. PhotoShop/LightRoom
+ [ ] Upload photos to GitHub (this issue/thread)
+ [ ] Write up the recipe!
  + [ ] Ingredients list
  + [ ] Process/steps
  + [ ] Any insightful tips/tricks

Once we have the content, we can figure out how to host it in the most SEO friendly way. 💭 
Currently considering WordPress: https://github.com/nelsonic/learn-wordpress/issues/5

## Context

At present, if we search for "how to make chia egg" on Google:
https://www.google.com/search?q=how+to+make+chia+egg
![image](https://user-images.githubusercontent.com/194400/165979391-207cc2bd-bf21-4075-b2c6-33093bb19dbc.png)

The top result is: https://minimalistbaker.com/make-chia-egg/
![image](https://user-images.githubusercontent.com/194400/165979253-4da5e3a2-d813-4e7d-bb20-97fd0ca3fb06.png)

But if you want actually _view_ the content, you first need to either "Accept All: 
![image](https://user-images.githubusercontent.com/194400/166079625-e67e9de7-659e-4029-83aa-8c4f5595ee8b.png)

The **Green** **`Accept All`** Call to Action (CTA) button in the Pop-up/Modal is a [Dark Pattern](https://usercentrics.com/knowledge-hub/dark-patterns-and-how-they-affect-consent/) designed to erode your privacy. 
If you click the button they want you click you will be agreeing to share your browser data with **133 3<sup>rd</sup> Parties** (see below).

You can see the list by clicking on "Manage Your Privacy" > "VENDORS":

![image](https://user-images.githubusercontent.com/194400/166079614-6eb96f39-07a4-4fbe-87f3-f4172493ede2.png)

1. 33Across
1. A.Mob
1. Active Agent (ADITION technologies GmbH)
1. AcuityAds Inc.
1. Ad360
1. ADARA MEDIA UNLIMITED
1. AdElement
1. Adform
1. Adobe Advertising Cloud
1. Adobe Advertising Cloud
1. Adobe Audience Manager, Adobe Experience Platform
1. Adobe Business Catalyst
1. Adobe Spark
1. AdTheorent, Inc
1. Akamai
1. Amazon
1. Amazon A9
1. Amazon Advertising
1. Amobee Inc.
1. AnyClip
1. Axel Springer Teaser Ad GmbH
1. BeeswaxIO Corporation
1. BIDSWITCH GmbH
1. Bidtellect, Inc
1. BidTheatre AB
1. Bing
1. Blis Media Limited
1. BritePool Inc
1. Carbon (AI) Limited
1. Centro
1. Centro
1. Chocolate Platform
1. Cloud Technologies S.A.
1. CMI Marketing, Inc. d/b/a CafeMedia
1. Comscore B.V.
1. Crimtan Holdings Limited
1. Criteo SA
1. DeepIntent, Inc.
1. Delta Air Lines
1. Delta Projects AB
1. DeltaX
1. Dentsu London Limited
1. Digital East GmbH
1. DoubleVerify Inc.​
1. dunnhumby Germany GmbH
1. DynAdmic
1. Emerse Sverige AB
1. EMX Digital LLC
1. Epsilon
1. Exponential Interactive, Inc d/b/a VDX.tv
1. Facebook
1. GetIntent
1. Google (non TCF)
1. Google Advertising Products 
1. Google Analytics
1. Google Analytics (Privacy Friendly)
1. Google Maps
1. Google Optimize
1. Google ReCaptcha
1. Google Tag Manager 
1. GumGum, Inc.
1. HUMAN
1. ID5 Technology Ltd
1. Index Exchange, Inc.
1. Integral Ad Science, Inc.
1. IPONWEB GmbH
1. Kargo Global Inc.
1. Kayzen
1. Knorex
1. Liftoff Mobile, Inc.
1. LinkedIn
1. LinkedIn Ireland Unlimited Company
1. LiquidM Technology GmbH
1. LiquidM Technology GmbH
1. LiveIntent 
1. LiveRamp, Inc.
1. LoopMe Limited
1. Magnite CTV, Inc.
1. Magnite, Inc.
1. Magnite, Inc. (Outstream)
1. Market Resource Partners LLC
1. Media.net Advertising FZ-LLC
1. Mediakeys Platform
1. MediaMath, Inc.
1. mediarithmics SAS
1. Mobile Professionals BV
1. Nativo, Inc.
1. NeuStar, Inc.
1. NextRoll, Inc.
1. Nielsen DAR 
1. Nielsen Marketing Cloud
1. OpenX
1. Oracle Data Cloud
1. Outbrain UK Ltd
1. PadSquad
1. Parrable
1. Platform161
1. Platform161 B.V.
1. Platform360
1. PubMatic, Inc.
1. PulsePoint
1. Quantcast International Limited
1. Rakuten Marketing LLC
1. remerge GmbH
1. Roxot
1. RTB House S.A.
1. Sharethrough, Inc
1. Sift Media, Inc
1. Simplifi Holdings Inc
1. Sizmek by Amazon
1. Smart Adserver
1. Sociomantic
1. Sonobi, Inc
1. Sovrn Holdings Inc
1. SpotX, Inc
1. StackAdapt
1. TabMo SAS
1. Taboola Europe Limited
1. TAPTAP Digital SL
1. Teads
1. The MediaGrid Inc.
1. The Procter & Gamble Company
1. The Trade Desk
1. travel audience GmbH
1. TripleLift, Inc.
1. Undertone
1. Unruly Group LLC
1. Xandr, Inc.
1. Yahoo
1. Yahoo EMEA Limited
1. Yieldmo, Inc.
1. Zemanta, Inc.
1. Zeta Global

I _wish_ I was making this up.  But I'm not. The default choice they want you to click "**Accept All**" will add so many trackers and share your data with so many [Data Brokers](https://www.youtube.com/watch?v=wqn3gR1WTcA) that will then monitor your activities across the web. You might not _care_ that other people know you have viewed a random recipe ... 
But ... you absolutely _should_ care about your own privacy and that of other people!

### SEO

Google _likes_ these websites because they all use Google Analytics and display Ads.
It will be interesting to see if we can "compete" with them given that we won't _ever_ have Ads.

Anyway, let's create this recipe and piece of content so we can link to it! 🙏

**Comment by Stephanymtr** [comment]
There are loads of other egg replacement recipes too: ground flax seed, applesauce, mashed banana .... the list is endless 😆 This is a great guide for me to get started. I just downloaded Chrome. Let's do it!

**Comment by Stephanymtr** [comment]
The Pretty Bee

The second result is https://theprettybee.com/chia-egg/
<img width="1065" alt="Screenshot 2022-05-03 at 12 04 14" src="https://user-images.githubusercontent.com/91985721/166442404-127a8d16-b46c-41e7-ad4d-4dac8097d967.png">

There are multiple ads on this webpage
<img width="1429" alt="Screenshot 2022-05-03 at 12 05 54" src="https://user-images.githubusercontent.com/91985721/166442689-646edd05-cc1e-4185-9b60-aca1c1b452a5.png">

It is not a long recipe page, the four photos are what makes it long. However, it is a chia egg recipe literally just water and chia.... It should be short anyways. 

The page contains a video on egg replacers... not just on chia egg. It is 35 seconds long, with annoying happy song in the background, no one is talking. You have no other option but to look at the screen and watch it. I personally prefer to play videos with someone talking in the background. It allows me to multitask in the kitchen. 


Some of the into questions:
WHAT IS A CHIA EGG REPLACER?
WHAT DOES A CHIA SEED EGG TASTE LIKE?
DO CHIA SEEDS NEED TO BE GROUND UP BEFORE USING?
HOW DO YOU MAKE A CHIA SEED EGG REPLACER?

>>recipe<<

They also share the nutritional value of a chia egg
along with 
WHERE CAN YOU FIND SAFE CHIA SEEDS?

**Comment by nelsonic** [comment]
Wow ... all those Ads! 🤮 
Just show us the content already ... 🙄 
(_thanks for capturing this. we can do **so much better**!_)

**Comment by Stephanymtr** [comment]
I'm really curios to know how many people exit out of these pages with all these ads, videos and SO MANY pictures because of those 2-5 seconds ish that takes for everything to load. Not everyone has access to new devices/high speed internet 🤔 💭

**Comment by Stephanymtr** [comment]
Eating Bird Food

The third result is: https://www.eatingbirdfood.com/chia-egg/

<img width="1436" alt="Screenshot 2022-05-03 at 17 27 34" src="https://user-images.githubusercontent.com/91985721/166498779-fe7cd336-d1e2-41ef-8255-470d1a10bb87.png">

If there was a contest for which of these websites had the most ads, I honestly wouldn't be able to tell. SO many ads! On top of all the ads, this one page had a pop up email invite window.... what do we think about this? 

<img width="1432" alt="Screenshot 2022-05-03 at 17 28 00" src="https://user-images.githubusercontent.com/91985721/166497772-4f153d08-7a7f-43ca-9fc8-a67e37876c33.png">

<img width="1439" alt="Screenshot 2022-05-03 at 17 28 28" src="https://user-images.githubusercontent.com/91985721/166497423-a1cf0616-c6a1-47be-80dc-d1c332be189a.png">

<img width="1435" alt="Screenshot 2022-05-03 at 17 34 36" src="https://user-images.githubusercontent.com/91985721/166498599-65801721-3b3b-4338-a3da-a5fcdbd911f9.png">


This page has beautiful theme, colour, font, AMAZING 4-5 photos... it's really pleasing to look at. I noticed all these pages have different size photos... some of them take up the entire page space....

<img width="1430" alt="Screenshot 2022-05-03 at 17 41 02" src="https://user-images.githubusercontent.com/91985721/166500327-6dca15ae-c761-44b2-a141-5be14ef5b67f.png">
<img width="1437" alt="Screenshot 2022-05-03 at 17 41 21" src="https://user-images.githubusercontent.com/91985721/166500351-ef2ae82b-ef45-41b2-b141-d8842fc1fc84.png">

 +++ alex is up... going finish up later

**Comment by Stephanymtr** [comment]
Bob's Red Mill

The fourth result: https://www.bobsredmill.com/recipes/how-to-make/chia-seed-egg-replacer/

<img width="1891" alt="Screenshot 2022-05-04 at 16 58 48" src="https://user-images.githubusercontent.com/91985721/166722234-95aec463-3e28-445d-b7cb-a50b56a216e5.png">

This one is a bit different than the others. Bob's Red Mill is an American brand of whole-grain foods. There are no ads, videos, tips/tricks, intro questions/bullet points. It's clean and straight to the point. There is only one picture. 

  
<img width="1910" alt="Screenshot 2022-05-04 at 16 52 09" src="https://user-images.githubusercontent.com/91985721/166721952-b0867467-0d4f-4129-b3ab-2f934492c0c7.png">

<img width="1009" alt="Screenshot 2022-05-04 at 16 52 39" src="https://user-images.githubusercontent.com/91985721/166721976-70333877-cad1-468c-af07-fdaa5e9a3c98.png">

**Comment by nelsonic** [comment]
Wow. up-sell central. 🙄 
Very curious what all these pages look like on Mobile ... 📱 
that's probably how _most_ people will be viewing the content. 💭

**Comment by Stephanymtr** [comment]
Detoxinista

5th result: https://detoxinista.com/how-to-make-flax-eggs-or-chia-eggs/

<img width="1920" alt="Screenshot 2022-05-04 at 17 02 09 (2)" src="https://user-images.githubusercontent.com/91985721/166722988-7eb3652e-0de7-4192-a2f9-5324f3fc8d38.png">

<img width="1920" alt="Screenshot 2022-05-04 at 17 09 51 (2)" src="https://user-images.githubusercontent.com/91985721/166724233-7122c173-ef16-4cf0-9384-16990595e8c9.png">

ads per usual.

Even though we Googled "how to make chia eggs" the title on this blog is : How to make flax eggs (vegan egg sub)

Some of the intro questions:
What is a Flax Egg?
Do Flax Eggs Really Work?
Flax eggs work well in:
Flax eggs don’t work well in:
How to Make a Flax Egg or Chia Egg
To Make One Flax Egg combine:
Recipes That Use Flax Eggs
>> recipe <<
<img width="1920" alt="Screenshot 2022-05-04 at 17 08 54 (2)" src="https://user-images.githubusercontent.com/91985721/166724017-ca6f00c3-94b2-46c0-b46f-613d8a91dd05.png">

they have 58 sec video with music in the background
<img width="945" alt="Screenshot 2022-05-04 at 17 14 30" src="https://user-images.githubusercontent.com/91985721/166724996-4bb2ff91-1a88-4f2c-9bcf-9a2f8e730247.png">

Post recipe questions/bullet points:
How do you use Flax Eggs in baking?
Which recipes call for flax and chia eggs?

**Comment by Stephanymtr** [comment]
Namely Marly!

The 6th result is: https://namelymarly.com/chia-egg/

<img width="1430" alt="Screenshot 2022-05-05 at 17 36 39" src="https://user-images.githubusercontent.com/91985721/166971518-2077a9e5-389b-4a53-abb5-63c5e8068b7d.png">
<img width="1433" alt="Screenshot 2022-05-05 at 17 37 07" src="https://user-images.githubusercontent.com/91985721/166971544-9e6c972a-a74a-4158-96e4-b0c27f4eb45a.png">
<img width="1438" alt="Screenshot 2022-05-05 at 17 37 29" src="https://user-images.githubusercontent.com/91985721/166971557-bc5d8760-9ea6-4ae7-9fd6-86abdd857c43.png">

Loads  of ads throughout the recipe:
<img width="1440" alt="Screenshot 2022-05-05 at 17 42 00" src="https://user-images.githubusercontent.com/91985721/166971861-156d6b56-fd5c-4ec8-8aff-b8c5abcd5a11.png">

It is a very long page considering the size of this recipe. They only have 4 photos (good quality), no video, but I believe the ads are what is making this long.

![Uploading Screenshot 2022-05-05 at 17.54.16.png…]()


Some their questions/ bullet points
How to Make a Chia Egg
Replacing Eggs in Baked Goods
When to not use Chia Eggs]
What is a chia egg?
Do chia seeds need to be ground up before using?
Can you replace flax egg with chia egg?
Chia Benefits
Ways to use a Chia Egg

**Comment by Stephanymtr** [comment]
Vegan Richa

The 7th result is: https://www.veganricha.com/recipe-pages/how-to-make-a-flax-egg-or-chia-egg/

<img width="1440" alt="Screenshot 2022-05-05 at 17 56 38" src="https://user-images.githubusercontent.com/91985721/166974700-a6c31275-842d-49a6-aac0-8eb3a1c5171f.png">
<img width="1440" alt="Screenshot 2022-05-05 at 17 56 54" src="https://user-images.githubusercontent.com/91985721/166974721-8640fe67-810e-4c7c-9127-88787fdcb884.png">

***** time is up, going to finish up this one later

**Comment by nelsonic** [comment]
Wow. Ads are _really_ obnoxious. 😕

**Comment by nelsonic** [comment]
Yeah, having _massive_ images is totally lame for the people viewing the content. Slow and wasteful. ⏳ 
Totally intrigued by the "Gelato University" ad you were served above ... 😜

**Comment by Stephanymtr** [comment]
Quick recap on what most of these websites/pages have in common:

- Introduction with questions/answer about the recipe
- Decent quality photos 
- Ads throughout the entire page
- Recipe:
Prep time
Total time
Servings
Ingredients list
Instructions 
some of them have short videos
Nutrition facts
A print and pin (Pinterest) button
- Link to other recipes/ social media accts
- Invitation to their email newsletter
- Comment section (I was very surprised to see so many comments)


[Eating Bird Food ](https://www.eatingbirdfood.com/chia-egg/) impressed me with their cute and good looking website.
<img width="1440" alt="Screenshot 2022-05-06 at 16 56 45" src="https://user-images.githubusercontent.com/91985721/167169435-eee821b1-0349-4d14-9e29-e440027e9768.png">
<img width="1440" alt="Screenshot 2022-05-06 at 16 56 53" src="https://user-images.githubusercontent.com/91985721/167169454-866e9a70-ea8a-4c41-82f6-842b26c2bdc1.png">

**Comment by Stephanymtr** [comment]
Alex might be waking up soon I just want to post some of the pictures I've taken so far ! They are NOT edited, cropped or anything. I still need to "chia eggs and make picture of the process as well." 
![20220519_113916.jpg](https://user-images.githubusercontent.com/91985721/169277355-4145d35b-8e02-44a8-9c2c-ba0fae7b3709.jpg)![20220519_113849.jpg](https://user-images.githubusercontent.com/91985721/169277365-460b3add-1517-4510-8265-44d6ec81abc5.jpg)![20220519_113740.jpg](https://user-images.githubusercontent.com/91985721/169277387-dc896798-4307-42d4-a376-d0623fa96fe2.jpg)![20220519_113614.jpg](https://user-images.githubusercontent.com/91985721/169277402-50960366-e060-47f9-a3e8-b8c5b1069ea1.jpg)![20220519_113516.jpg](https://user-images.githubusercontent.com/91985721/169277431-d6ae02bc-7cab-4dee-86a0-4b5cb8b69c04.jpg)![20220519_113511.jpg](https://user-images.githubusercontent.com/91985721/169277458-eded747b-7a08-42f8-84db-b0d791910340.jpg)![20220519_113525.jpg](https://user-images.githubusercontent.com/91985721/169277414-4f6688c1-c2af-475e-8b05-f8c5bc5cd11a.jpg)![20220519_113511.jpg](https://user-images.githubusercontent.com/91985721/169277493-52438434-3b68-4265-858c-95ab5e7e96cb.jpg)![20220519_113437.jpg](https://user-images.githubusercontent.com/91985721/169277508-c34cd230-6759-4e38-8c22-126f8cb7df58.jpg)

**Comment by Stephanymtr** [comment]
I don't have a solid plan on taking pictures of the chia eggs (and other recipes) YET. I would like for the ingredients/meals to be the main focus of each photo. I envision a white/minimalistic background being a fine idea. Although I have seen some really cool shots of recipes like chocolate chip cookies with a milk jug, a coffee mug and a couple of other props in the background.  Adding props can be fun and useful to add depth on a complete white background. However, since we are starting now, something more simple and straight forward might be ideal (question mark ?)

My basic plan is to:

- [ ] take photos under natural light 
- [ ] minimize clutter by focusing on what's important
- [ ] colors true to life 
- [ ] _still brainstorming_

I took a few photos with my Samsung Galaxy Note 10 Plus this morning while A was napping: 

We might not sure these specifically, but I have to say I like the simpleness. Open to comments and suggestions :)

**Comment by nelsonic** [comment]
I know this is retro …
![7C2CDB53-959F-4D07-893F-951BC723A919](https://user-images.githubusercontent.com/194400/169354482-c2914c30-30a6-43a1-8628-a5ad573a20e5.jpeg)

![49286A93-82DA-4817-97CF-E2F5FF626D5A](https://user-images.githubusercontent.com/194400/169354619-9d7f4b77-6f1b-477e-b48c-3eb76c97dcd4.jpeg)


A *book* … 📖 🤷🏼‍♂️ 
Can’t I just learn all of this from YouTube? 😜
Yes, but YouTube is distraction central… 📺🙄
Books are self-contained guides that show you *exactly* where to start your quest. 💡

**Comment by Stephanymtr** [comment]
I have been looking for a creditable Nutrition Label maker that we can use for our upcoming recipes. I bumped into a couple websites like https://www.recipal.com/ which is a FDA and CFIA - compliant nutrition fact labels, recipe costing, and inventory management. It's not free 🙄 20 bucks per recipe!! 
<img width="1209" alt="Screenshot 2022-05-20 at 09 54 08" src="https://user-images.githubusercontent.com/91985721/169492507-8f7beded-1a81-46da-becb-bad0b04511e0.png">
https://www.recipal.com/pricing

Maybe we could (should?) use a food label that is complied with EU food label regulations, BUT then again, regardless of which country/continent we choose to create this "official" label from, they are only required to be used for pre-packed food.... why spend money on this when we aren't going to be selling pre-packed food ?! https://europa.eu/youreurope/business/product-requirements/food-labelling/nutrition-declaration/index_en.htm#shortcut-2
<img width="1255" alt="Screenshot 2022-05-20 at 10 18 38" src="https://user-images.githubusercontent.com/91985721/169497746-145de8f4-c994-4d6a-bd14-2a71256956bb.png">

NONE of the recipe blogs I shared above had a credible source under their Nutrition Label (no source shared for that matter actually). So the question is 'how accurate are these nutrition labels they have?' These bloggers might just be trying to "include" readers who are trying to be health conscious about the food they prepare and eat regardless of how accurate/precise their information really is. 
<img width="396" alt="Screenshot 2022-05-20 at 10 38 08" src="https://user-images.githubusercontent.com/91985721/169500792-33746f1d-8e39-4ce0-b194-e75633475ec5.png">
<img width="1048" alt="Screenshot 2022-05-20 at 10 38 37" src="https://user-images.githubusercontent.com/91985721/169500804-29da951f-fbfd-412c-af79-bb178724cdbb.png">
<img width="727" alt="Screenshot 2022-05-20 at 10 39 02" src="https://user-images.githubusercontent.com/91985721/169500813-74856da2-cc7b-428f-85c4-a3785f34456c.png">

We could use a free label maker calculator online and have a 'nutrition information is a rough estimate' warning (like some bloggers do) or just omit including a Nutrition Fact table in our recipe blogs for now. 💭

**Comment by nelsonic** [comment]
@Stephanymtr _thank you_ for bringing up the topic of nutrition info.
We very much want to include nutrition info in our recipes. 🙏 
https://www.recipal.com/ looks like it's for people wanting to create labels for their **_packaged_ foods** ...
This definitely deserves a _separate/dedicated_ issue which we can link to from here.

The FDA provides a comprehensive database of nutritional info for free: https://fdc.nal.usda.gov/download-datasets.html
Then we can write our own calculator, see: https://github.com/dwyl/learn-tdd
But we should definitely open the issue so that we can _study_ the nutrition info labels
and understand what is required from a calculator.

**Comment by Stephanymtr** [comment]
### Some more ideas:

- [ ] So as you can see on my first draft I posted above, https://github.com/iteles/blw-baby/issues/25#issuecomment-1131808418 I included a comment section. Let's try to make it easy to comment on our blog. No CAPTCHAs or required logins, if possible. 
- [ ]  We could then respond to their comment publicly / even comment on their blogs - if they have one. 
- [ ] Providing social media sharing buttons will make it easy for people to share our content online. Saying thank you when others promote our work would be a good follow up to that.
- [ ]  It would be fantastic if we could add a spot in each of our future recipe posts for visitors to leave their reviews.  ⭐ ⭐ ⭐ ⭐ ⭐ It looks neat on Google results: 
<img width="696" alt="Screenshot 2022-06-08 at 13 03 17" src="https://user-images.githubusercontent.com/91985721/172615532-2dafc7ab-4506-451f-b18f-bda6fa9b76bf.png">

**Comment by Stephanymtr** [comment]
### Content Creation Update
In order to complete this first draft, we will need a nutritional label as well as some photos. I took a couple of photos to start getting the hang of it, but haven't done a round two yet. The kitchen counters over at BMH have been installed and soon everything in the kitchen will have its own place, so it should be much easier/faster for me to find ingredients/tools to get this (and future) photoshoots done.  I have been doing some reading and researching ideas that I can implement, so going to share here a list of things I will need next time I work on this. The initial plan is to "GET IT DONE ASAP" so if you guys feel that my photos/content need work, just let me know, and we will revisit it & redo it. 

Photos needed
- [ ] Photos of just chia seeds
- [ ] Photos of all ingredients - before 
- [ ] Photos of all ingredients - on measuring cups/spoons
- [ ] Photos of chia egg - showing consistency

Will need
- [ ] cute container to place chia seeds (clear glass/white ceramic?/wood bowl)
- [ ] small cute glass for water 
- [ ] small spoon (preferably wooden)
- [ ] 1 tbsp measuring spoon 
- [ ] 2.5 tbsp = 37 ml = (little over) 1/8 measuring cup = small cup for water  

How/when

- [ ] take same photo from different angles: flat lays and overhead shots
- [ ] constantly unlock exposure to create a well-lit image.
- [ ] take advantage of natural light staying away from the bright sun as it creates hard shadows
- [ ] background ideas: wooden tray, concrete floor, neutral-colored tile with an interesting pattern.
- [ ] Close-up and macro shots will avoid the need for so many props and useful for simple recipes like this one. Can also try the bokeh effect when you focus on the object and the surrounds (even if super busy) aren't taking over/blurred
- [ ] Overhead lights like 'strobe lights' can be great especially when taking picture from up top. Try the LED strips and those mobile flashlights w magnets A likes to play with... might need some sort of tripod.
- [ ] 'Rule of Thirds' use grid when taking these photos and place the focal point where the lines intersect
- [ ]tip: If the area is well lit, use ISO 100. At the height of the day, an f/2.8 at ISO 100 will give around 1/1000 of a second, if not more. try the pro settings on my phone.
- [ ]  finally, add a bit of pizzazz with different props until we feel we found a/our style ex:herbs, garnishes, chunks of bread, some extra sauce, coarse salt or pepper to sprinkle onto surface etcccc
