### ISSUE TITLE
Research: Unbreakable Glass or Stainless Non-spill "Sippy Cup" or Sports Bottle

### ISSUE THREAD

**Issue by nelsonic** [iteles/blw-baby#26]
We _hypothesize_ that **`A*`** is waking up in the middle of the night _thirsty/dehydrated_ 
because whenever we give him water to drink he gulps it down! 

We need to:
(a) create a "water station" in the kitchen where he can get as much water as he needs without making a mess 
and 
(b) provide him with a **non-spill** ("_sippy_") cup with a straw that doesn't come out.

There should be one in the bedroom next to his bed at all times 
so that he can drink at night without needing to wake an adult.

And there should be one near him all day. e.g. take to the park, in the car, or in the house.
We could attach it to the pram on a string + karabina so that he can always reach it and doesn't need to ask for water.
The cup-holder on the pram should be for the adult, not the child.

# Todo

+ [ ] Research at least 3 products that could meet our needs. 
+ [ ] Ideally they should be made of Glass (_with a rubber bumper to prevent immediate breakage!_) or stainless steel. 
   If we cannot find a cup in these materials either keep looking or consider a "BPA Free" plastic as a last resort
+ [ ] Don't care about cost. If it's €100 per cup that's fine as long as it's _exceptional_ quality/durability.

**Comment by nelsonic** [comment]
First product suggestion:  Thinkbaby Stainless Steel Thinkster Bottle
https://www.amazon.com/thinkbaby-Thinkster-Steel-Bottle-Silver/dp/B00VXV94JS?th=1

![image](https://user-images.githubusercontent.com/194400/167042033-9f73cb16-94b1-4207-bcdb-991b0a90436a.png)

Stainless Steel is good for durability and hygiene. 
Not so great for seeing how much is remaining in the bottle ...
Amazon reviews are good.

Available in PT from this _horrible_ website:
https://pt.iherb.com/pr/think-thinkbaby-thinkster-of-steel-bottle-orange-1-straw-bottle-9-oz-260-ml/65130
![image](https://user-images.githubusercontent.com/194400/167042173-ec553545-e4e7-4fbd-9b3a-e8f5913708d1.png)

@iteles I'm sure you've done some research into baby cups. Please share if there's _already_ an issue.  🙏

**Comment by iteles** [comment]
I've done some research and although I don't like the handles on the thinkbaby one, I've found nothing _better_.

Here are the best options I found that I discounted:

### 1. Camelbak
I love this one BUT then figure out you have to ***bite*** the straw before you suck out the water. Not a mechanism we want to introduce (anything with biting) at this stage 😭 
https://www.camelbak.com/recreation/shop/bottles/kids/eddy-kids-12-oz-bottle-insulated-stainless-steel/CB-2284.html
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/4185328/169797664-6a6f2c94-9924-4268-9bca-af51da161761.png">


### 2. Munchkin
Looks great but the reviews say they are hard to clean so the straws get mouldy and you can't buy replacement straws. Hard pass.

https://www.amazon.co.uk/Munchkin-Stainless-Steel-Straw-Green/dp/B07SWSN7C6
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/4185328/169797238-e3e39ac1-176a-4048-8505-1a87e95ed28e.png">

Also discounted this one because the spout is more like a sippy cup than a straw which I'm not interested in:
https://eu.waterdrop.com/products/toddler-bottle?variant=39474734989430
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/4185328/169797877-aea3f55f-7428-453f-ab18-0edd4b022bf2.png">

**Comment by Stephanymtr** [comment]
How do you guys feel about the sippy cups you both have researched ? I see this has been assigned to me, just wondering what you guys would like me to do next. Keep on looking ? Thanks!

**Water Station**
I put together a water station that quickly failed miserably (for obvious reasons lol) I didn't have the chance to "introduce" the concept to Alex. I should have also warned everyone that looks after him to "get ready"  as it is very important to reinforce "this water is for drinking" and if he keeps playing with it (which he will in the beginning) consistently say "let's find some water that we can play with".  Don't let him play with the drinking water. Once the station has been set up, staying close with him is ideal.  If you can see that he is going to pour (or play with) the drinking water, say no or take the water away. I THINK some strict reinforcement should only need to last a short time before he (hopefully!) gets the message.  

Note: Spilling is an important part of the process. He will learn to refine his motor control through the desire not to spill eventually.

- [ ] Water dispenser
- [ ] Non-slip pad under the water source - might be useful since we wouldn't fill up w/ water more than 1/4 of the dispenser ?!
- [ ] Water dispenser spill tray
- [ ] Cleaning cloth
- [ ] Glasses - plural, yes! In to help introduce this new concept, I was thinking that us guides should drink from his water station as a way of showing him what he's supposed to be doing?!  🤷 aka Modelling 
- [ ] Mat - to be placed under the table

**Water Bottle Attachment to Stroller Bumper Bar Inspo**:
https://www.amazon.com/Universal-Stroller-Tray-Exclusive-Attachment/dp/B09BG5RNLV
![image](https://user-images.githubusercontent.com/91985721/172587654-27e8c8d1-a3ce-4f36-a128-347636459aef.png)

**Comment by iteles** [comment]
@Stephanymtr It was just a research issue for now!
Could you please grab your comment above and open a separate issue on a water station?

In the meantime, I saw this bottle at a store that I was already having to purchase something else from (an air layer for the sweltering hot car seat):
https://www.tartaruguita.pt/produto/garrafas-termicas-com-palhinha-e-tampa-extra-350ml-fresk/
<img width="973" alt="image" src="https://user-images.githubusercontent.com/4185328/175094985-98570c03-4235-4df4-84fa-8a8e095dc902.png">

It's a terribly non-illustrative picture and I couldn't find better but it is:
- Stainless steel
- 350ml so not too heavy for now
- Thermal
- Has a rigid straw top that flips up and down so it's not easily destroyed by toddler teeth
- A flexible straw bottom on the inside of the bottle so it doesn't need to be tipped for drinking
- Doesn't have handles either side so it's more 'real world' and less 'baby'
- Straw tops and straws are sold separately (a HUGE plus that is rare for these kinds of bottles) meaning you don't have to buy a whole new bottle when one straw/top gets wrecked
- A separate non-straw top for transport as well

It's supposed to be water tight even with the straw top on but I haven't tested this yet (this may be why there is also a non-straw top for transport purposes).

I thought this was dragging a bit so I just purchased one (and a spare straw top + straw) to test.

Leaving this open so Stephany can move her comment to a new issue and then we can close this until we need to open it again.

**Comment by Stephanymtr** [comment]
@iteles I moved it. You can close this issue 😃 Thank you!

**Comment by nelsonic** [comment]
we should only close this issue when we have _published_ our research as a post. 💭

**Comment by iteles** [comment]
Added the `documentation` label and removed the priority-1 in aid of your latest comment @nelsonic 👍
