### ISSUE TITLE
Research and Organise Cloth/Reusable Diaper Laundry Service

### ISSUE THREAD

**Issue by nelsonic** [iteles/blw-baby#27]
## This isn't about _Weaning_ ... But it is about "Baby", Leadership <br />and what happens to the Food when it comes out the other end ... ⏳ 

This might not _appear_ to be a "BLW" issue on the surface, 
because it's not strictly about _weaning_, 
but it _is_ about the _other_ side of the digestive system ... 💩 
and therefore it's **_highly_ relevant** to other parents and caregivers. 
It's widely known in Montessori methodology that cloth/reusable diapers 
are _vastly_ superior for potty/toilet-training 
because they don't deprive the child of the sensation of "wetness"
the way that disposable diapers do.

It's been more than a year of reuse-able diapers with our 👶 
and the experience has been simultaneously enlightening/rewarding
and ***`sh!tty`*** ... 🙄 

## The problem 💩 🙉 🤦‍♂️ 

I'm opening this issue because one didn't already exist and it _really_ needs to!
I [searched](https://github.com/issues?q=is%3Aopen+is%3Aissue+author%3Aiteles+archived%3Afalse+diapers) but didn't find anything containing a _systematic_ approach to solving this problem.
I haven't spent as much time researching this as @iteles has. But she hasn't had time to open this issue, so here it is.

### The True Cost of Reusable Diapers 💸 🔥 

Each day our 👼 who is not yet fully potty-trained requires **5-7 diaper changes**. 
Inside these diapers we have 1-3 "gifts" 🎁 (💩)  per day.

Recently had a 3-gift day: 🎉 
![image](https://user-images.githubusercontent.com/194400/167749406-386fff96-6b6f-4640-98ee-893e5c585345.png)

Most of the time it's 2 ...
Each of these diapers requires "scraping" into the toilet before the diaper can be washed in the machine.
This anything from 1-5 mins as - excuse the detail - some times the excreta is more _persistent_.

I cannot help but think that there's a _much_ better way of doing this.
Or at least that we could find someone `else` who would be willing to do this job 
for (_considerably_) less cash than Senior Software Engineer's [hourly rate](https://github.com/dwyl/learn-elixir/issues/102#issuecomment-1105416646) ... 💭 

# "_The price of anything is the amount of life you exchange for it_." <br />~ Henry David Thoreau

If we add up all the _time_ that is consumed on processing a batch of diapers.
It's _significantly_ more expensive to use reusable diapers than disposables.
**10 mins** of my time (_which I regularly spend on this in the evenings_) 
would _easily_ pay for a **40 pack** of **Bambo Nature** diapers.
We are _definitely_ not doing this to _save_ money! 

https://www.naturitas.pt/p/mama-e-bebe/higiene-do-bebe/fraldas/fraldas-t5-12-18-kg-eco-44-unidades-bambo
![image](https://user-images.githubusercontent.com/194400/167750164-63691365-69d7-4f73-9cce-3956606006e8.png)

_obviously_ this issue is not the place to debate switching to disposables. 
I think we need to do an in-depth study on the _actual_ environmental cost of reusables first.

What we do need is a *system* that means I (Nelson) don't have to deal with the soiled diapers.
As much as I want to "chip in" and "do my part". 
I feel like somehow my skills (as a top 1% in the _world_ engineer) are somehow undervalued doing this task ...
Like getting a Micheline Star Chef to operate the french fries station in a McDonalds kitchen ... 
or getting Lewis Hamilton washing cars ... 

# _Solution_? 🙏 

### Lavanderia Self Service Top Clean

The closest laundry service is "Lavanderia Self Service Top Clean".  https://goo.gl/maps/QwLVyvHwvmjqLYKG6
![image](https://user-images.githubusercontent.com/194400/167724441-8412e198-a04b-4877-9452-015873aadbd8.png)

The reviews are good: https://bussola-pt.com/173840/lavanderia-self-service-top-clean
![image](https://user-images.githubusercontent.com/194400/167728994-c0ae87cb-67fc-473c-a22a-aed843999c97.png)
The only 4-star review which drag down the average is from this genius who wrote: "Excellent service":

![image](https://user-images.githubusercontent.com/194400/167739189-99150b15-ce36-49c5-982f-4ce0320fa0d6.png)

 > If the service is "excellent" then why did you dock a star without an explanation?! [anyway ...](https://xkcd.com/386/) 🙄 

### Mr Jeff - Laundry App with Collection service

The next option to consider is this App/Site called Mr Jeff (_strange name, must mean something to someone ..._)
https://jeff.com/pt/mrjeff/store/braga-saovitor/
![image](https://user-images.githubusercontent.com/194400/167739388-a640e016-990a-495e-b75e-05de65da91f8.png)

# Todo

+ [ ] **Contact** both Lavanderia Self Service Top Clean and Mr Jeff and find out if they do diapers. 
  if they do, find out how much they charge. If it's less than €1/diaper we use it _immediately_. 
+ [ ] **Document** ***ALL*** of the **steps** required to "process" the reusable/cloth diapers from start to finish.
  + [ ] ***Delegate*** this task to someone else and compensate them generously. 
  e.g. 2x min wage. (cause we know it's a "crappy" job ...)

**Comment by iteles** [comment]
I have, as you rightly say, researched this extensively.

## The main issue
The wash routine for cloth diapers is the main source of _every_ cloth diaper issue from smells to rashes to leaks.

The cloth diaper groups online are ***filled*** with people bemoaning issues with their cloth diapers that turn into nothing but 'let's trouble shoot your wash routine' posts.

They depend on:
+ The hardness of your water
+ The detergent that you use, both type and quantity
  + This is _different_ for _every single_ detergent (thanks manufacturers)
  + There are a number of detergents that shouldn't be used full stop (eco and 'sensitive' ones as a general rule)
+ Your washing machine
  + Whether it weighs your clothes
  + Whether it's 'eco'
  + Whether you can find a combination of programs that put in enough water and do enough rinsing for a good clean - we're talking about human waste after all
  + Top loading or front loading
+ The number of days you leave between washes
+ How full your wash load is
+ Your ability to trouble shoot when you first have an issue and adapt
+ If the wrong products are used (detergents with more than 5% soap, harsh chemicals or fabric softeners) your diapers can be irreparably ruined or require a very Laborious process to 'revive'.


Because of this, wash routines are ***extremely delicate beasts*** and trusting this to someone else with the task is tricky because the propensity to get back something that is ruined or no longer functional/absorbent is high (simply because what you're asking of them is not _usual_).

## Cloth diaper laundry service
I have both researched this extensively and asked every group I am a part of and as of today, there is no full service in existence in Portugal that picks up your diapers, washes them and returns them to you.

They are not common enough in this country.

Most people have never heard of them and a lot of _medical professionals_ who see babies every day have never even seen one before 🤷‍♀️ 

## Self service laundrettes
The vast VAST majority of these have the following fundamental problems for cloth diapers:
1. 99% control the detergent that you use in the washes:
  + They control the amounts (automatic in the machines)
  + There is no possibility to have a wash without detergent 
2. The majority force the use of fabric softeners (which destroy the absorbency of a diaper, much like they do those of towels)
3. They minimise the amount of water used in each wash cycle - great for the environment, terrible for diapers
4. There are 3 separate wash cycles required in the wash routine - this means whoever is washing the diapers is stuck at the laundrette for an age

Numbers 1 and 2 make washing diapers in 99% of self service laundrettes impossible. 
Numbers 3 and 4 make it much harder.

## Laundry service (not used to diapers)
There are two main questions here:
+ Can you ***trust*** a laundry service to follow your instructions to the letter when they think they're the experts and know best so they can totally skip the unnecessary steps in your requirements? Especially with regards to the use of specific detergents and products? I would have a very hard time trusting a service whose sole purpose is profit to do this correctly.
  + Side note: Working out how much detergent is the correct amount for their size of machines (especially if they're not always the same) is also an issue
+ Will they willingly use their machines to clean human waste?
  + Most folks don't understand cloth diapers and hygiene is often cited as a factor by those more ignorant 

This _could_ possibly work with a small family-run laundermat with extremely nice people who we could eventually trust though. Maybe!

**Comment by nelsonic** [comment]
Logging this info as an _example_ instance of the processing task.
My only reasoning for logging is so that we can create a _system_. 📝 
I don't mind being a "cog" in that machine ... ⚙️ 
But as I noted above, I feel my time _might_ be better spent generating cash to pay someone `else` to do this ... 💭 

Today was another 3-present day 🎁 🎉 
![image](https://user-images.githubusercontent.com/194400/167945252-98b3013f-2b10-40dd-aa9f-9755784e7467.png)

Took me **`12min 50sec`** to "process" the 3 diapers.
I put the the stopwatch on only when I was ready to start to not "inflate" the amount of time.
![image](https://user-images.githubusercontent.com/194400/167945412-060ce21f-a5d2-48b9-8269-d7a4c108799d.png)

Took out the inserts and stoped the timer as soon as I put the diapers in the laundry basket:

![image](https://user-images.githubusercontent.com/194400/167945958-2e5002e2-e118-4311-8cbf-40d6703532c7.png)

definitely didn't take any _extra_ time. In fact I would _challenge_ someone to do it faster than I did.
I rinsed the liners to remove the _sticky/dried_ bits. (`#TMI`...?)

3 different brands/types of diaper. #28 ... 💭 

In this case (at this stage in the process) I don't think it would have been much faster if there was a single type of diaper ... where the time-suck happens is in "setting up" ("montar") the diapers. A better diaper would require _considerably_ less "setup" time. 

The _ideal_ diaper would have an insert system that used _biodegradable/flushable_ ultra-soft hemp liners: #29

**Comment by iteles** [comment]
Specifically on the 💩 situation there is an 'easy fix'. 
We just use disposable liners. 

I've always preferred reusable ones but seeing as we are back to non-ploppable 💩s, we should just use disposable liners and wash the ones that have pee only. 

I will set this up tomorrow.

**Comment by nelsonic** [comment]
@iteles from your reply above, it sounds like what we need is a _system_ ... 
with a _simple_ sequence of steps that literate (but perhaps not necessarily university educated) person can follow.

**Comment by nelsonic** [comment]
[**21 months**](https://www.timeanddate.com/date/durationresult.html?d1=11&m1=05&y1=2022&d2=12&m2=2&y2=2024)  later no system. no more babysitters (with university degrees!) to help. Inês is doing the diaper "assembly" herself ... again, this is perfectly "fine" for someone who _doesn't_ value their time like a Gov Employee that cannot _think_ of a "side-hustle" to do in their "spare" time... But for someone who is supposed to be running a [company](https://github.com/dwyl) and has dozens of high priority/value tasks [assigned](https://github.com/issues?q=is%3Aopen+is%3Aissue+assignee%3Aiteles) to them for _years_ without progress, it's a bit of a kick-in-the teeth to the person/people who are [_waiting_ for progress](https://github.com/dwyl/home/issues?q=assignee%3Aiteles+is%3Aopen) on those issues. 😢 

For me, by _far_ the most tragic aspect in all this is how _little_ time it would take to _define_ a **system** 
and then _recruit_ some eco-conscious person _with_ a small child, low on cash and high on "spare" time to help.

https://www.olx.pt/d/anuncio/empregada-domstica-c-referncias-IDH0I6J.html
<img width="1192" alt="image" src="https://github.com/iteles/blw-baby/assets/194400/d5291233-2a09-4698-af3e-781c46590080">

Literally [_everything_](https://github.com/dwyl/home/issues/244) `else` @iteles _can_ be doing with her time is more valuable than "assembling" diapers.
As a "[knowledge worker](https://en.wikipedia.org/wiki/Knowledge_worker)", knowing the _value_ of your time and the [Opportunity Cost](https://en.wikipedia.org/wiki/Opportunity_cost) of _not_ doing the higher/highest value task, is the _first_ thing you should think about before starting any activity.

On a _personal_ note: Inês ***insists*** on running the washing machine at night when "_**electricity** is **cheaper**_":

<img width="1062" alt="image" src="https://github.com/iteles/blw-baby/assets/194400/7a32a2ed-1937-42af-8d51-7abb3d6ecfc8">

The noise & vibration from the machine _often_ wakes me up as it did tonight. 🛌 📳 😠  
For as long as Inês has known me, she's known that I have _severe_ [insomnia](https://github.com/dwyl/sleep/issues?q=is%3Aissue+is%3Aopen+insomnia). 
When I am woken in the middle of the night I find it near-impossible to go back to sleep.

This has happened more times than I can _count_ in the last 3 years as again, Inês ***insists*** on running the machine at night despite me _begging_ her to _not_ do it. 😢 
So I've had more bad nights in the last 3 years than I can _count_. 
And _trust_ me when I say that ***ONE*** bad night and subsequent "unproductive" day 
is more expensive to us than ***TEN YEARS*** of running the washing machine during the day when it can't wake me!!
And yet, Inês ***insists*** on doing it. I don't know if it's stubbornness or _spite_. But it's _killing_ me. 😢
