### ISSUE TITLE
Ultimate Sugar-Free/Healthy/Baby-Friendly Banana Bread  

### ISSUE THREAD

**Issue by Stephanymtr** [iteles/blw-baby#33]
> I'm going to follow Nelson's instructions from the Chia Seed Content Creation Issue for this one as well. 

### Todo
**Research**
- [ ]  Take a look at the existing web pages/sites listed on the first page of Google results (max 8)
- [ ]  Use an incognito Chrome (or Brave) window to avoid any cookies/trackers
- [ ]  Screenshot the first thing you see when you open the page e.g. the annoying cookie modal/prompt below. Once you've dismissed the cookie noise, take another screenshot of actual content to show the layout, any Ads, and show how much cruft there is on the page. i.e. do they get straight to the point or is there a lot of noise?

### Create!
Once you have looked at the available top recipes for a Banana Bread and uploaded all the screenshots for the research.
- [ ] Plan the photograph we are going to take for our recipe:
- [ ]  What background do you want to use, do you want anything else in the frame?
- [ ]  Take the photos of raw ingredients, process and final result
- [ ]  Do any necessary post-processing of images e.g. PhotoShop/LightRoom
- [ ]  Upload photos to GitHub (this issue/thread)
- [ ]  Write up the recipe!
- [ ]  Ingredients list
- [ ]  Process/steps
- [ ]  Any insightful tips/tricks

**Comment by Stephanymtr** [comment]
### Context
At present, if we search for "healthy banana bread" on Google:

<img width="1440" alt="Screenshot 2022-06-08 at 17 06 23" src="https://user-images.githubusercontent.com/91985721/172664846-acbdda7d-d5f0-4539-a2d3-11fcfd3d5032.png">
<img width="1440" alt="Screenshot 2022-06-08 at 17 06 27" src="https://user-images.githubusercontent.com/91985721/172664874-e9269315-07e1-45ce-ba89-91ba2a5c892d.png">

There are many words we can use to describe this recipe: Vegan/Fast/Easy, etc. I mentioned a few more in the title.

**Comment by Stephanymtr** [comment]
Cookie + kate

The first result is: https://cookieandkate.com/healthy-banana-bread-recipe/

<img width="1440" alt="Screenshot 2022-07-19 at 11 55 48" src="https://user-images.githubusercontent.com/91985721/179734334-271d2b5d-781a-4434-b565-48397b592e9c.png">

Front page:
<img width="1440" alt="Screenshot 2022-07-19 at 11 56 50" src="https://user-images.githubusercontent.com/91985721/179734522-e199cd97-a24c-436f-bd32-30b2aff9e3c1.png">
<img width="1440" alt="Screenshot 2022-07-19 at 11 57 49" src="https://user-images.githubusercontent.com/91985721/179734982-22287be5-6e09-4442-95aa-b53425a5c44b.png">

There are many ads in this page:
<img width="1440" alt="Screenshot 2022-07-19 at 11 58 43" src="https://user-images.githubusercontent.com/91985721/179735016-64943008-4bf4-495c-8eee-97f22e54fdae.png">
<img width="1440" alt="Screenshot 2022-07-19 at 11 59 09" src="https://user-images.githubusercontent.com/91985721/179735037-4d81dcee-5b9a-433c-8958-d2060f62e114.png">
<img width="1440" alt="Screenshot 2022-07-19 at 11 59 46" src="https://user-images.githubusercontent.com/91985721/179735041-bff17ab9-1bdb-424c-9f50-432933353de1.png">

They have about 11 photos. There are a few intro paragraphs.
<img width="1440" alt="Screenshot 2022-07-19 at 12 05 40" src="https://user-images.githubusercontent.com/91985721/179736164-e5f73e59-3ef6-44ec-8af7-b91c491315fc.png">


continue later
 
Some of the intro questions:

**Comment by Stephanymtr** [comment]
Gimme Delicious
Healthy Moist Banana Bread
2nd: https://gimmedelicious.com/healthy-moist-banana-bread/

Despite it being the 2nd result, this page has a 'Not secure warning'. It contains way more ads than usual. 

<img width="1440" alt="Screenshot 2022-07-22 at 09 44 00" src="https://user-images.githubusercontent.com/91985721/180401497-115c1f3a-0efc-4009-abba-ef27b95c9190.png">
<img width="1440" alt="Screenshot 2022-07-22 at 09 44 12" src="https://user-images.githubusercontent.com/91985721/180401503-730cfc20-18d3-4805-8419-c218d25415b0.png">
<img width="1440" alt="Screenshot 2022-07-22 at 09 44 21" src="https://user-images.githubusercontent.com/91985721/180401510-b6433be6-f3fd-40d2-a968-da137fa72e1c.png">

**Comment by Stephanymtr** [comment]
Tastes Better from Scratch
Healthy Banana Bread
3rd: https://tastesbetterfromscratch.com/skinny-banana-bread/

<img width="1440" alt="Screenshot 2022-07-22 at 09 57 07" src="https://user-images.githubusercontent.com/91985721/180407902-ddcb12ed-24c9-4338-a3da-6f0329eea562.png">
<img width="1440" alt="Screenshot 2022-07-22 at 10 19 45" src="https://user-images.githubusercontent.com/91985721/180407906-5a13581e-a037-47c3-9da5-04ddc6188751.png">

**Comment by Stephanymtr** [comment]
Chocolate Covered Katie
Healthy Banana Bread
4th: https://chocolatecoveredkatie.com/healthy-banana-bread/

<img width="1440" alt="Screenshot 2022-07-22 at 10 46 02" src="https://user-images.githubusercontent.com/91985721/180415528-0ed27bf5-5696-4a3d-88e7-43bc75283041.png">
<img width="1440" alt="Screenshot 2022-07-22 at 10 46 10" src="https://user-images.githubusercontent.com/91985721/180415546-fb5e830a-8a8b-4711-8f58-eb8e2cb4f3e2.png">
<img width="1440" alt="Screenshot 2022-07-22 at 10 53 48" src="https://user-images.githubusercontent.com/91985721/180415558-29436e94-2c48-4af2-9bfb-6e0354a293e5.png">

couple of points:
-Healthy banana bread for breakfast or snack
-Simple whole grain banana bread
-Banana loaf ingredients
-Can the healthy banana bread recipe be vegan?
-How to make banana bread

<img width="1440" alt="Screenshot 2022-07-22 at 11 01 11" src="https://user-images.githubusercontent.com/91985721/180416969-2b296b19-c3ca-4625-bdf9-8d6ad96ede0f.png">

loads of ads, pinterest pins, reviews

**Comment by Stephanymtr** [comment]
BBC Good Food
Healthy Banana Bread
5th: https://www.bbcgoodfood.com/recipes/healthy-banana-bread

This is a very short page with a couple of ads, a comment and review section, 

<img width="1440" alt="Screenshot 2022-07-22 at 11 39 45" src="https://user-images.githubusercontent.com/91985721/180422855-e7fec040-c940-4e9e-91f5-a00635908003.png">
<img width="1440" alt="Screenshot 2022-07-22 at 11 42 55" src="https://user-images.githubusercontent.com/91985721/180422990-630dca04-2cc2-45cb-9ad9-cdeb587cb060.png">
<img width="1440" alt="Screenshot 2022-07-22 at 11 41 12" src="https://user-images.githubusercontent.com/91985721/180422867-8773d63b-e57b-4913-a40d-31f2594c8569.png">

**Comment by Stephanymtr** [comment]
⭐ Ambitious Kitchen
Best Ever Healthy Banana Bread Recipe
6th: https://www.ambitiouskitchen.com/my-favorite-healthy-banana-bread-recipe/

This page's combination of font, images and content is aesthetically pleasing.

<img width="1440" alt="Screenshot 2022-07-22 at 11 51 47" src="https://user-images.githubusercontent.com/91985721/180425849-6ecdccd4-2911-4753-b4a9-798d344653f8.png">
<img width="1440" alt="Screenshot 2022-07-22 at 11 51 51" src="https://user-images.githubusercontent.com/91985721/180425858-02f8c906-933b-4244-a912-6ffa07378e1a.png">
<img width="1440" alt="Screenshot 2022-07-22 at 11 52 00" src="https://user-images.githubusercontent.com/91985721/180425864-8a9cf520-6b54-4a81-ae57-c59c17b2632c.png">

_It's a long long long page._ 
- Intro
- Ingredients in this healthy banana bread recipe
- Tips for making delicious healthy banana bread
- Customize your banana bread
- How to make this healthy banana bread dairy free
- Suggestions for gluten free banana bread
- How to make this healthy banana bread into muffins
- How to store banana bread
- How to freeze banana bread
- Other banana recipes you might like

- Comment and review section

<img width="1440" alt="Screenshot 2022-07-22 at 12 09 43" src="https://user-images.githubusercontent.com/91985721/180427541-5e85fad7-14ba-4189-bc4a-64027194a719.png">
<img width="1440" alt="Screenshot 2022-07-22 at 12 10 03" src="https://user-images.githubusercontent.com/91985721/180427554-e631949c-9094-43fe-96b6-1a81a26d5ab0.png">

**Comment by Stephanymtr** [comment]
Kristine's Kitchen
The Best Healthy Banana Bread Recipe
7th: https://kristineskitchenblog.com/healthy-banana-bread-recipe/

This page contains the usual: ads, couple of photos, a video, a comment and rating section.
<img width="1440" alt="Screenshot 2022-07-22 at 12 22 13" src="https://user-images.githubusercontent.com/91985721/180429398-9f64dcf0-ace0-405f-8c85-018826180fee.png">
<img width="1440" alt="Screenshot 2022-07-22 at 12 22 17" src="https://user-images.githubusercontent.com/91985721/180429412-e0d17b68-13f3-45d3-b9e9-b13f571a1616.png">
<img width="1440" alt="Screenshot 2022-07-22 at 12 23 05" src="https://user-images.githubusercontent.com/91985721/180429421-5b8b5929-1c38-4045-8a4b-c2ba5c8a3c14.png">
<img width="1440" alt="Screenshot 2022-07-22 at 12 23 22" src="https://user-images.githubusercontent.com/91985721/180429424-cd3f2b5b-fc49-43c4-bdc7-365fe6b524d7.png">

Not as long, but it still had a few points:
-HOW TO MAKE THIS HEALTHY BANANA BREAD RECIPE
-HOW TO FREEZE BANANA BREAD
-BAKING TIPS FOR BANANA BREAD

**Comment by Stephanymtr** [comment]
Kim's Cravings
HEALTHY BANANA BREAD
8th: https://www.kimscravings.com/healthy-banana-bread/


<img width="1440" alt="Screenshot 2022-07-22 at 12 36 33" src="https://user-images.githubusercontent.com/91985721/180431860-8f66b95d-0840-4679-98fa-52b16eb3ae5f.png">
<img width="1440" alt="Screenshot 2022-07-22 at 12 36 43" src="https://user-images.githubusercontent.com/91985721/180431873-2f1f5777-0a2b-4d79-a696-fd11646e0c10.png">
<img width="1440" alt="Screenshot 2022-07-22 at 12 38 40" src="https://user-images.githubusercontent.com/91985721/180431882-a62c1fca-e49f-4f60-860a-e54775fe7501.png">
<img width="1440" alt="Screenshot 2022-07-22 at 12 40 12" src="https://user-images.githubusercontent.com/91985721/180431967-f77e2848-2504-4025-ae7d-6821d33bb475.png">

Points:
- INTRO
- INGREDIENTS NEEDED
- HOW TO MAKE THIS RECIPE
- BAKER’S TIPS
- RECIPE VARIATIONS
- FREQUENTLY ASKED QUESTIONS
- MORE GREAT BREAD RECIPES

This page contains the same layout as all the others: Nutrition information, comment and rating section, social media pins, photos, ads, and a video
